// <auto-generated />
using System;
using GymMasterAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymMasterAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529060300_agregarModulos")]
    partial class agregarModulos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymMasterAPI.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("MiembroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiembroId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("GymMasterAPI.Models.HorarioModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("HorariosModulo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaSemana = "Lunes",
                            HoraFin = "08:30",
                            HoraInicio = "07:00",
                            ModuloId = 1,
                            Nivel = "Principiante"
                        },
                        new
                        {
                            Id = 2,
                            DiaSemana = "Miércoles",
                            HoraFin = "08:30",
                            HoraInicio = "07:00",
                            ModuloId = 1,
                            Nivel = "Principiante"
                        },
                        new
                        {
                            Id = 3,
                            DiaSemana = "Viernes",
                            HoraFin = "09:30",
                            HoraInicio = "08:00",
                            ModuloId = 1,
                            Nivel = "Avanzado"
                        },
                        new
                        {
                            Id = 4,
                            DiaSemana = "Sábado",
                            HoraFin = "11:00",
                            HoraInicio = "09:00",
                            ModuloId = 1,
                            Nivel = "Todos los niveles"
                        },
                        new
                        {
                            Id = 5,
                            DiaSemana = "Martes",
                            HoraFin = "08:00",
                            HoraInicio = "07:00",
                            ModuloId = 2,
                            Nivel = "Todos los niveles"
                        },
                        new
                        {
                            Id = 6,
                            DiaSemana = "Jueves",
                            HoraFin = "18:00",
                            HoraInicio = "17:00",
                            ModuloId = 2,
                            Nivel = "Principiante"
                        },
                        new
                        {
                            Id = 7,
                            DiaSemana = "Miércoles",
                            HoraFin = "20:00",
                            HoraInicio = "19:00",
                            ModuloId = 2,
                            Nivel = "Intermedio"
                        },
                        new
                        {
                            Id = 8,
                            DiaSemana = "Sábado",
                            HoraFin = "11:30",
                            HoraInicio = "10:00",
                            ModuloId = 2,
                            Nivel = "Todos los niveles"
                        });
                });

            modelBuilder.Entity("GymMasterAPI.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especialidad = "Boxeo",
                            EstaActivo = true,
                            NombreCompleto = "Carlos Cordova",
                            Turno = "Matutino y Vespertino"
                        },
                        new
                        {
                            Id = 2,
                            Especialidad = "Zumba y ritmos latinos",
                            EstaActivo = true,
                            NombreCompleto = "Valeria Ríos",
                            Turno = "Matutino y Vespertino"
                        });
                });

            modelBuilder.Entity("GymMasterAPI.Models.Membresia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Membresias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Costo = 50m,
                            Descripcion = "Acceso completo al gimnasio por un día. Ideal para visitantes o prueba.",
                            DuracionDias = 1,
                            Nombre = "Plan Diario"
                        },
                        new
                        {
                            Id = 2,
                            Costo = 200m,
                            Descripcion = "Una semana completa de entrenamiento sin restricciones.",
                            DuracionDias = 7,
                            Nombre = "Plan Semanal"
                        },
                        new
                        {
                            Id = 3,
                            Costo = 600m,
                            Descripcion = "Un mes entero con acceso completo. La mejor opción para resultados reales.",
                            DuracionDias = 30,
                            Nombre = "Plan Mensual"
                        },
                        new
                        {
                            Id = 4,
                            Costo = 150m,
                            Descripcion = "Acceso diario al gimnasio más un módulo de Boxeo o Zumba a tu elección.",
                            DuracionDias = 1,
                            Nombre = "Diario + Módulo"
                        },
                        new
                        {
                            Id = 5,
                            Costo = 300m,
                            Descripcion = "Una semana con acceso al gimnasio y clases de Boxeo o Zumba incluidas.",
                            DuracionDias = 7,
                            Nombre = "Semanal + Módulo"
                        },
                        new
                        {
                            Id = 6,
                            Costo = 700m,
                            Descripcion = "El plan más completo. Un mes con gimnasio y clases de Boxeo o Zumba.",
                            DuracionDias = 30,
                            Nombre = "Mensual + Módulo"
                        });
                });

            modelBuilder.Entity("GymMasterAPI.Models.Miembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MembresiaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MembresiaId");

                    b.ToTable("Miembros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gym.com",
                            EstaActivo = true,
                            FechaInscripcion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Administrador",
                            Password = "admin123",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "recepcion@gym.com",
                            EstaActivo = true,
                            FechaInscripcion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Recepción Principal",
                            Password = "recepcion123",
                            Rol = "Recepcionista"
                        });
                });

            modelBuilder.Entity("GymMasterAPI.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Badge = "BX",
                            Color = "#aa3bff",
                            Descripcion = "Aprende técnicas de defensa personal, mejora tu condición física y libera el estrés.",
                            InstructorId = 1,
                            Nombre = "Boxeo"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Badge = "ZB",
                            Color = "#ff3b9a",
                            Descripcion = "Baila, quema calorías y diviértete con ritmos latinos. Clases para todos los niveles.",
                            InstructorId = 2,
                            Nombre = "Zumba"
                        });
                });

            modelBuilder.Entity("GymMasterAPI.Models.Asistencia", b =>
                {
                    b.HasOne("GymMasterAPI.Models.Miembro", "Miembro")
                        .WithMany()
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("GymMasterAPI.Models.HorarioModulo", b =>
                {
                    b.HasOne("GymMasterAPI.Models.Modulo", "Modulo")
                        .WithMany("Horarios")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("GymMasterAPI.Models.Miembro", b =>
                {
                    b.HasOne("GymMasterAPI.Models.Membresia", "Membresia")
                        .WithMany()
                        .HasForeignKey("MembresiaId");

                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("GymMasterAPI.Models.Modulo", b =>
                {
                    b.HasOne("GymMasterAPI.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("GymMasterAPI.Models.Modulo", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
